# Generated by Django 4.2.4 on 2023-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactformsubmission_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
            ],
        ),
    ]
