# Generated by Django 4.2.4 on 2023-09-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
